### ISSUE TITLE
last paragraph gets parsed two times

### ISSUE THREAD

**Issue by jbeyerstedt** [getkirby/plugins#10]
The last paragraph (or the part after the last line break) of the last column is inserted another time after the last column, but before the closing `</div>` of the surrounding container.
So this text in the panel:

```
(columns...)

### column 1
At vero eos et accusam.

Duis autem vel eum iriure. 
    
++++
    
### column 2
Stet clita kasd gubergren.

Lorem ipsum dolor sit amet. 
    
(...columns)
```
leads to this html code:
```
<div class="columns columns-2"><div class="column"><h3>column 1</h3>
<p>At vero eos et accusam.  </p>
<p>Duis autem vel eum iriure.</p></div><div class="column"><h3>column 2</h3>
<p>Stet clita kasd gubergren.  </p><p>Lorem ipsum dolor sit amet.</p></div>
<p>Lorem ipsum dolor sit amet.</p></div></div>
```
And there seems to be one closing `</div>` too much.

As mentioned, it´s the same issue with line breaks instead of paragraphs. I tested this on a brand new installation of kirby 2.0.6.

**Comment by julianhutton** [comment]
Having this same issue. Would love to get a fix.

**Comment by grahamharper** [comment]
+1

**Comment by bastianallgeier** [comment]
Hey guys, 

sorry for the delay. This is related to a problem with parsedown and is fixed in the latest version, which is now available on the develop branch. It will be in the next stable release.
