### ISSUE TITLE
Columns not working on PHP versions prior to 5.4.9

### ISSUE THREAD

**Issue by puleddu** [getkirby/plugins#11]
Any version of php prior to 5.4.9 does not split on four plusses.
http://sandbox.onlinephpfunctions.com/code/59fc226e61bd1e92c9928509587d31358fc66fba

Is there any workaround – a part from updating PHP, which is not immediate in my situation.

**Comment by lukasbestle** [comment]
Hm, that seems to be caused by the older PCRE library version used in older PHP versions.

My guess is that the `\R` character class is the reason for the problem. Replacing it with an old-school `(\n|\r\n)` might solve the problem (unfortunately I can't test it right now).

**Comment by puleddu** [comment]
Thanks for the suggestion, I created a pull request #12 that solves also another issue.
