### ISSUE TITLE
Column plugin duplicates last content

### ISSUE THREAD

**Issue by NECKRHINOS** [getkirby/plugins#14]
Hello

I'm experiencing strange behavior with the latest version of the columns plugin, #13 : The last line of the content's txt file where columns are used gets duplicated outside the columns.

Kirbytext:
```
Text: Lorem ipsum dolor sit amet.

(columns...)

**John Snow**
Bastard

(email: john.snow@the-wall.org text: Drop a line)

++++

**Hodor**
Hodor

(link: www.hodor.com text: Hodor)

(...columns)
```

HTML:
```
<div class="columns columns-2">
  <div class="column">
    <p><strong>John Snow</strong>
    <br>Bastard</p>
    <p><a href="mailto:john.snow@the-wall.org">Drop a line</a></p>
  </div>
  <div class="column">
    <p><strong>Hodor</strong>
    <br>Hodor</p>
    <p><a href="http://www.hodor.com">Hodor</a></p>
  </div>
  <!-- NOTE: THIS IS THE DUPLICATED CONTENT -->
  <p><a href="http://www.hodor.com">Hodor</a></p>
</div>
```

Anyone else having this problem as well?

**Comment by jbeyerstedt** [comment]
Hi, this is a duplicate of #10. I had reported this issue two week ago and it´s fixed in the current release of the develop branch.

**Comment by NECKRHINOS** [comment]
Whoops, thanks for the heads up. Sorry for double posting ;-)
