### ISSUE TITLE
Kirby Images

### ISSUE THREAD

**Issue by wachilt** [getkirby/plugins#15]
**GitHub** https://github.com/medienbaecker/kirby-images

> The `images` field can be used to edit groups of images very easily by drag-and-drop. Simply take an image from the sidebar and drop it on the field. You can also reorder images inside the field, not linked to the regular order.

![images](https://user-images.githubusercontent.com/7975568/29234770-9f686324-7ef9-11e7-8c37-f53e2848c846.gif)

**Comment by bastianallgeier** [comment]
This is now part of the v3 core
