### ISSUE TITLE
Columns plugin isn't working for me 

### ISSUE THREAD

**Issue by xypaul** [getkirby/plugins#19]
The last paragraph always get repeated, so for this code:
![screenshot 2015-04-27 17 04 42](https://cloud.githubusercontent.com/assets/2549828/7343024/82bfd344-ecff-11e4-99e3-45ca1dc9d5c1.png)

The actual produced html has duplicated the paragraph from the last column.
![screenshot 2015-04-27 17 04 14](https://cloud.githubusercontent.com/assets/2549828/7343029/8709388c-ecff-11e4-8f16-be134858d231.png)

**Comment by xypaul** [comment]
The problem only seems to occur if there are <h> elements inside the columns.... weird.

**Comment by yeeeen** [comment]
I'm having this problem too.

**Comment by lukasbestle** [comment]
This is a duplicate of #10, #14 and #16. Please try using the current development version of Kirby from the `develop` branches.

**Comment by xypaul** [comment]
@lukasbestle thanks
