### ISSUE TITLE
breaks panel?

### ISSUE THREAD

**Issue by puckey** [getkirby/plugins#23]
when I include the cdn plugin, my panel .js and .css is rewritten to: http://my.cdn.domain.com/assets/stylesheets/panel.css - causing a 404 and breaking the panel

**Comment by puckey** [comment]
My settings:

c::set('cdn.assets', 'http://cdn.studiomoniker.com/assets');
c::set('cdn.content', 'http://cdn.studiomoniker.com/');
c::set('cdn.thumbs', 'http://cdn.studiomoniker.com/thumbs');

**Comment by jensfranke** [comment]
just a quick-fix:

cdn.php:

```
$url = preg_replace_callback('!.*?\/assets\/(.*)$!', function($match) {

  if (str::contains($match[0], 'panel'))
    return c::get('cdn.panel.assets') . '/' . $match[1];
  else
    return c::get('cdn.assets') . '/' . $match[1];
}, $url);
```

config.php:

c::set('cdn.panel.assets', 'http://cdn.my-domain.com/panel/assets');

**Comment by notandrewkaye** [comment]
Thanks for the fix @jensfranke that fix worked perfectly.

**Comment by bastianallgeier** [comment]
This is fixed now.
