### ISSUE TITLE
Feed (plugin): guid must be a full URL warning/error + Self reference doesn't match document location

### ISSUE THREAD

**Issue by afincato** [getkirby/plugins#32]
Beside issues [#21](https://github.com/getkirby/plugins/issues/21),
there are two other problems with the feed plugin:
both are concerning the `link()` and or `url()` tag, I suppose, in `feed.php`.

Validation output of **getkirby.com/blog/feed** [here](https://validator.w3.org/feed/check.cgi?url=http://getkirby.com/feed).

First:
> guid must be a full URL, unless isPermaLink attribute is false: blog/security-update-2-1-1
`<guid>blog/security-update-2-1-1</guid>`

Here the plugin spits out the correct url the line above the one requested by the feed validator:
`<link>http://getkirby.com/blog/security-update-2-1-1</link>`
`<guid>blog/security-update-2-1-1</guid>`

Second:
> In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.
line 12, column 82: Self reference doesn't match document location
`... rel="self" type="application/rss+xml" />`

Here instead the url should match **getkirby.com/blog/**, but stops just at the root:
`<atom:link href="http://getkirby.com" rel="self" type="application/rss+xml" />`

**Comment by oroco** [comment]
:+1:

**Comment by afincato** [comment]
Got some time to look into it and resolved one of the two errors.
To correctly validate the feed, it is necessary to edit `template.php` inside the `feed` folder.

At line 19, change this
`<guid><?php echo xml($item->id()) ?></guid>`
into
`<guid isPermaLink="false"><?php echo xml($item->id()) ?></guid>`

since if we want to use the `guid` tag as an `id` and not a real url tag (as it happens with the line above), we have to explicitly declare that it's not a permalink, hence adding `isPermaLink="false"` within the `guid` tag.

Alternatively, but to me it feels not the right direction to take, we can replace
`$item->id()` with `$item->url()`, as it is in the line above, which for reference looks like this
`<link><?php echo xml($item->url()) ?></link>`

**Comment by afincato** [comment]
Feed Validator says it's not a real problem, but I just wanted to understand what was the reason behind also this other small error and it was quite easy to get it.

Quoting the problem from the first post
> In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.
line 12, column 82: Self reference doesn't match document location
... rel="self" type="application/rss+xml" />

go to line 9 of `template.php` and change this line from
`<atom:link href="<?php echo xml($url) ?>" rel="self" type="application/rss+xml" />`
to
`<atom:link href="<?php echo xml($link) ?>/feed" rel="self" type="application/rss+xml" />`
so, to be precise replace `<?php echo xml($url) ?>` with 
`<?php echo xml($url) ?>` and add after it `/feed`

In this way the url correctly refers to the blog's (or podcast or whatever) feed.
