### ISSUE TITLE
Video not working with Kirby 2.3?

### ISSUE THREAD

**Issue by danst0** [getkirby/plugins#43]
I have the sublime plugin installed, however it stopped working recently... Might this be due to my update to Kirby 2.3?
What can I do to fix this?

Daniel

**Comment by lukasbestle** [comment]
How did it stop working? Do you get any error message?

**Comment by danst0** [comment]
I do not get any error message, there is just no [html output](https://forum.getkirby.com/t/sublime-video-whats-going-wrong/4625)

**Comment by lukasbestle** [comment]
I'm closing this as discussion continues in the forum. Please reopen this issue once it is confirmed that there is a bug with the plugin.
