### ISSUE TITLE
Remove develop branch as it’s stale

### ISSUE THREAD

**Issue by anselmh** [getkirby/plugins#45]
To avoid confusion with branches for contributors I think it would make sense to delete the current `develop` branch as it’s stale anyway.

**Comment by lukasbestle** [comment]
Actually the whole repo is stale and the plugins have been moved to the getkirby-plugins organization. Bastian was going to delete this repo, I will ask him about this.

**Comment by anselmh** [comment]
Ah, hm. Lots of plugins on http://getkirby-plugins.com/ list this as the source repo. 

You should usually move the repository via github’s transfership option to avoid duplicates like this and redirect users but this is likely too late by now :D thanks for the notice though!

**Comment by lukasbestle** [comment]
Well, that would not work as we did not move the repo but split it up. :)
Thanks for letting us know about getkirby-plugins.com, we will contact the site owner.
