### ISSUE TITLE
Multiple columns

### ISSUE THREAD

**Issue by NECKRHINOS** [getkirby/plugins#8]
Hej

Another question: Is it possible to use multiple columns right after another i. e. like this:

```
(columns...)

Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

++++

Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.

(...columns)

(columns...)

Nullam dictum felis eu pede mollis pretium. Integer tincidunt.

++++

Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.

++++

Nam eget dui. Etiam rhoncus. Maecenas tempus.

(...columns)
```

So that I could do 2 columns first and then 3 columns right afterwards. For now, this doesn't seem to work. Any chance of making this usable? :-)

**Comment by bnomei** [comment]
Yeah, I would also love to have that feature!

**Comment by puleddu** [comment]
+1 That's what I'd like to achieve also.

**Comment by puleddu** [comment]
I created a pull request #12 which fixes this.
